services:

  backend:
    build:
      context: ./backend
    container_name: forgeml_backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped

  db:
    image: postgres:16

    container_name: forgeml_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forgeml

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  postgres_data: